# nginx proxy address - http://172.17.0.1:8082

name: tt-rss
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  tt-rss:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    pull_policy: always
    container_name: tt-rss-app
    restart: always
    logging: *default-logging
    networks:
      - tt-rss
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8082:80"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: tt-rss-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      TTRSS_DB_TYPE: pgsql
      TTRSS_DB_HOST: tt-rss-db
      TTRSS_DB_PORT: 5432
      TTRSS_DB_NAME: ${DB_CREATE_DATABASE_NAME:-tt-rss}
      TTRSS_DB_USER: ${DB_USER_NAME:-tt-rss}
      TTRSS_DB_PASS: ${DB_USER_PASS:-changeme_db_password}
      TTRSS_SELF_URL_PATH: http://${BASE_HOST_NAME:-$HOSTNAME}:8082
      TTRSS_SINGLE_USER_MODE: 0
      TTRSS_SIMPLE_UPDATE_MODE: 0
      ADMIN_USER_PASS: ${APP_ADMIN_PASS:-changeme_admin_password}
    volumes:
      - ./volumes/data/tt-rss:/data
      - ./volumes/config/tt-rss:/config
    depends_on:
      tt-rss-db:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://tt-rss-app:80'
      - 'cloudflare.hostname=tt-rss.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.tt-rss-app.entrypoints=http'
      - 'traefik.http.routers.tt-rss-app-secure.tls=true'
      - 'traefik.http.routers.tt-rss-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.tt-rss-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.tt-rss-app.middlewares=tt-rss-app-https-redirect'
      - 'traefik.http.routers.tt-rss-app-secure.entrypoints=https'
      - 'traefik.http.routers.tt-rss-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.tt-rss-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.tt-rss-app-secure.service=tt-rss-app'
      - 'traefik.http.services.tt-rss-app.loadbalancer.server.port=80'

  tt-rss-db:
    image: postgres:latest
    pull_policy: always
    container_name: tt-rss-db
    restart: always
    logging: *default-logging
    networks:
      - tt-rss
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: tt-rss-db
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-tt-rss}
      POSTGRES_USER: ${DB_USER_NAME:-tt-rss}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./volumes/data/db/postgres/tt-rss:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tt-rss:
    name: tt-rss
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
